name: Build Aseprite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout builder repo
        uses: actions/checkout@v4

      - name: Checkout Aseprite source
        uses: actions/checkout@v4
        with:
          repository: aseprite/aseprite
          submodules: recursive
          path: aseprite

      - name: Locate Visual Studio
        shell: powershell
        run: |
          $vs = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest `
            -products * `
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -property installationPath

          echo "VS_PATH=$vs" >> $env:GITHUB_ENV

          Write-Host "Found Visual Studio:"
          Write-Host $vs

      - name: Enable MSVC environment
        shell: cmd
        run: |
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64

          where cl
          cl

      - name: Download Skia
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip `
            -OutFile skia.zip

          Expand-Archive `
            -Path skia.zip `
            -DestinationPath skia

      - name: Clean build folder
        shell: powershell
        run: |
          Remove-Item `
            -Recurse `
            -Force `
            aseprite\build `
            -ErrorAction SilentlyContinue

      - name: Configure CMake
        shell: cmd
        run: |
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64

          cd aseprite
          mkdir build
          cd build

          cmake ^
            -G Ninja ^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
            -DCMAKE_IGNORE_PATH=C:\mingw64\bin;C:\Strawberry\c\bin ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR=%GITHUB_WORKSPACE%\skia ^
            -DSKIA_LIBRARY_DIR=%GITHUB_WORKSPACE%\skia\out\Release-x64 ^
            -DSKIA_LIBRARY=%GITHUB_WORKSPACE%\skia\out\Release-x64\skia.lib ^
            ..

      - name: Build Aseprite
        shell: cmd
        run: |
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64

          cd aseprite\build

          ninja aseprite

      - name: Package Aseprite
        shell: powershell
        run: |
          Compress-Archive `
            -Path aseprite\build\bin\* `
            -DestinationPath aseprite-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows-x64
          path: aseprite-windows.zip
